#!/usr/bin/env python
import os, os.path, sys

pidFile = "supercast.pid"

execfile("supercast.conf");

if len(sys.argv) > 1:
    execfile(sys.argv[1])
if os.path.exists(pidFile):
   os.system("kill `cat " + pidFile + "`")
   os.remove(pidFile)
